# data augmentation
dataset:
  common:
    NAME: Line_seg
    data_root:  /home/tyy/TYY/Data/point_data/line/line_trainval_npy #/home/tyy/TYY/Data/point_data/line/line_ice #/userhome/zyx/dataset/pointcloud/s3dis__for_pointnext/s3disfull #/dev/shm/MEMORY_DATA/s3disfull
    test_area: 1 #5
    voxel_size: 0.64
  train:
    split: train
    voxel_max: 40000
    loop: 30  # here, the training has been looped 30 times. therefore, the training epochs do not need much.
    presample: False
  val:
    split: val
    voxel_max: 40000
    presample: False
  test:
    split: test
    voxel_max: 40000
    presample: False 

feature_keys: x,heights
num_classes: 2
batch_size: 4
val_batch_size: 1

dataloader:
  num_workers: 12 #6

datatransforms:
  train: [ChromaticAutoContrast, PointsToTensor, PointCloudScaling, PointCloudXYZAlign, PointCloudRotation, PointCloudJitter, ChromaticDropGPU, ChromaticNormalize]
  val: [PointsToTensor, PointCloudXYZAlign, ChromaticNormalize]
  vote: [ChromaticDropGPU]
  kwargs:
    color_drop: 0.2  # 颜色丢失率为 0.2，用于 ChromaticDropGPU 转换
    gravity_dim: 2  # 重力维度设为 2，用于 PointCloudXYZAlign 转换
    scale: [0.9, 1.1]  # 缩放范围在 0.9 到 1.1 之间，用于 PointCloudScaling 转换
    angle: [0, 0, 1]  # 旋转角度设为 [0, 0, 1]，用于 PointCloudRotation 转换
    jitter_sigma: 0.005  # Jitter 方差设为 0.005，用于 PointCloudJitter 转换，加入随机扰动
    jitter_clip: 0.02  # Jitter 裁剪值设为 0.02，用于 PointCloudJitter 转换


# ---------------------------------------------------------------------------- #
# Training cfgs
# ---------------------------------------------------------------------------- #
val_fn: validate
ignore_index: null 
epochs: 50

cls_weighed_loss: False

criterion_args:
  NAME: CrossEntropy
  label_smoothing: 0.2

optimizer:
 NAME: 'adamw'  # performs 1 point better than adam
 weight_decay: 1.0e-4

# lr_scheduler:
sched: cosine
warmup_epochs: 0

# min_lr: 1.0e-5 #1.0e-5 #
# lr: 0.002 #0.01 # LR linear rule.

min_lr: 1.0e-5 #
lr: 0.01 # LR linear rule.

grad_norm_clip: 10
use_voting: False
# ---------------------------------------------------------------------------- #
# io and misc
# ---------------------------------------------------------------------------- #
log_dir: 'lineseg'
save_freq: -1 # save epoch every xxx epochs, -1 only save last and best. 
val_freq: 1

wandb:
  project: PointMetaBase-S3DIS

save_pred: True
visualize: True
